from application import db 
from application.models import Players

db.drop_all()
db.create_all()

new_player = Players(player = "Mohamed Salah")
db.session.add(new_player)
new_player = Players(player = "Sadio Mane")
db.session.add(new_player)
new_player = Players(player = "Trent Alexander-Arnold")
db.session.add(new_player)
new_player = Players(player = "Kevin De Bruyne")
db.session.add(new_player)
new_player = Players(player = "Raheem Sterling")
db.session.add(new_player)
new_player = Players(player = "Sergio Aguero")
db.session.add(new_player)
new_player = Players(player = "Timo Werner")
db.session.add(new_player)
new_player = Players(player = "Kai Havertz")
db.session.add(new_player)
new_player = Players(player = "Hakim Ziyech")
db.session.add(new_player)
new_player = Players(player = "Marcus Rashford")
db.session.add(new_player)
new_player = Players(player = "Bruno Fernandes")
db.session.add(new_player)
new_player = Players(player = "Paul Pogba")
db.session.add(new_player)
db.session.commit()